[package]
name = "strand"
version = "0.0.0"
description = "A strand-like git GUI"
authors = ["Benji Grant"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.19", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = "2.0.0-rc.12"
sqlx = { version = "0.7", features = [ "runtime-tokio", "sqlite" ] }
tauri-specta = { version = "2.0.0-rc.5", features = ["typescript"] }
tauri-plugin-shell = "2.0.0-beta.5"
tauri-plugin-store = "2.0.0-beta.6"
tauri-plugin-dialog = "2.0.0-beta.7"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
