CREATE TABLE IF NOT EXISTS git_command_log (
  id INTEGER PRIMARY KEY NOT NULL,
  command TEXT NOT NULL,
  command_type INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  repository_id INTEGER NOT NULL REFERENCES repository(id) ON DELETE CASCADE
);
