/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function localBranches() {
    return invoke()<LocalBranch[]>("local_branches")
}

export type UpstreamTrack = { Delta: [number, number] } | "InSync" | "Gone"
export type GitHash = string
export type LocalBranch = { head: boolean; name: string[]; upstream_name: string[]; upstream_track: UpstreamTrack; hash: GitHash }
