name: TypeScript checks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**"
      - "biome.json"
      - "index.html"
      - "package.json"
      - "tailwind.config.js"
      - "tsconfig.*"
      - "vite.config.ts"
      - "pnpm-lock.yaml"
      - ".github/workflows/checks-ts.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm i
      - run: pnpm biome ci --reporter=github --error-on-warnings

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm i
      - run: pnpm tsc
