name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  covector:
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.covector.outputs.releaseId }}
      commandRan: ${{ steps.covector.outputs.commandRan }}
      shouldPublish: ${{ steps.covector.outputs.published-strand }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for use of git history
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install
      - uses: jbolda/covector/packages/action@covector-v0
        id: covector
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: version-or-publish
          createRelease: true
          draftRelease: true

      # If versioning (creating a version PR)
      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        if: steps.covector.outputs.commandRan == 'version'
      - name: set Cargo.toml version
        run: |
          sed -i 's/^version = .*/version = "${{ steps.package-version.outputs.current-version }}"/' Cargo.toml
          cargo update -w
        working-directory: src-tauri
        if: steps.covector.outputs.commandRan == 'version'
      - name: create pr
        uses: peter-evans/create-pull-request@v6
        if: steps.covector.outputs.commandRan == 'version'
        with:
          title: Publish New Version
          commit-message: Publish new version
          labels: release
          branch: release
          body: ${{ steps.covector.outputs.change }}

  build:
    needs: covector
    if: needs.covector.outputs.commandRan == 'publish' && needs.covector.outputs.shouldPublish == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # ARM
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest # Intel
            args: '--target x86_64-apple-darwin'
          - platform: ubuntu-22.04
            args: ''
          - platform: windows-latest
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - run: npm uninstall -g yarn && npm install -g corepack
        if: matrix.platform == 'windows-latest'
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - uses: dtolnay/rust-toolchain@stable
        with:
          # targets only needed on mac builds
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: install ubuntu dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - run: yarn install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI: false
        with:
          releaseId: ${{ needs.covector.outputs.releaseId }}
          args: ${{ matrix.args }} --verbose

  release:
    runs-on: ubuntu-latest
    needs: [covector, build]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.covector.outputs.releaseId }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false
            })
